/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// OrganizationTokenResponse struct for OrganizationTokenResponse
type OrganizationTokenResponse struct {
	OrganizationId *int64 `json:"organizationId,omitempty"`
	AccessToken *string `json:"accessToken,omitempty"`
	TokenId *string `json:"tokenId,omitempty"`
	Description *string `json:"description,omitempty"`
}

// NewOrganizationTokenResponse instantiates a new OrganizationTokenResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationTokenResponse() *OrganizationTokenResponse {
	this := OrganizationTokenResponse{}
	return &this
}

// NewOrganizationTokenResponseWithDefaults instantiates a new OrganizationTokenResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationTokenResponseWithDefaults() *OrganizationTokenResponse {
	this := OrganizationTokenResponse{}
	return &this
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *OrganizationTokenResponse) GetOrganizationId() int64 {
	if o == nil || isNil(o.OrganizationId) {
		var ret int64
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationTokenResponse) GetOrganizationIdOk() (*int64, bool) {
	if o == nil || isNil(o.OrganizationId) {
    return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *OrganizationTokenResponse) HasOrganizationId() bool {
	if o != nil && !isNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given int64 and assigns it to the OrganizationId field.
func (o *OrganizationTokenResponse) SetOrganizationId(v int64) {
	o.OrganizationId = &v
}

// GetAccessToken returns the AccessToken field value if set, zero value otherwise.
func (o *OrganizationTokenResponse) GetAccessToken() string {
	if o == nil || isNil(o.AccessToken) {
		var ret string
		return ret
	}
	return *o.AccessToken
}

// GetAccessTokenOk returns a tuple with the AccessToken field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationTokenResponse) GetAccessTokenOk() (*string, bool) {
	if o == nil || isNil(o.AccessToken) {
    return nil, false
	}
	return o.AccessToken, true
}

// HasAccessToken returns a boolean if a field has been set.
func (o *OrganizationTokenResponse) HasAccessToken() bool {
	if o != nil && !isNil(o.AccessToken) {
		return true
	}

	return false
}

// SetAccessToken gets a reference to the given string and assigns it to the AccessToken field.
func (o *OrganizationTokenResponse) SetAccessToken(v string) {
	o.AccessToken = &v
}

// GetTokenId returns the TokenId field value if set, zero value otherwise.
func (o *OrganizationTokenResponse) GetTokenId() string {
	if o == nil || isNil(o.TokenId) {
		var ret string
		return ret
	}
	return *o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationTokenResponse) GetTokenIdOk() (*string, bool) {
	if o == nil || isNil(o.TokenId) {
    return nil, false
	}
	return o.TokenId, true
}

// HasTokenId returns a boolean if a field has been set.
func (o *OrganizationTokenResponse) HasTokenId() bool {
	if o != nil && !isNil(o.TokenId) {
		return true
	}

	return false
}

// SetTokenId gets a reference to the given string and assigns it to the TokenId field.
func (o *OrganizationTokenResponse) SetTokenId(v string) {
	o.TokenId = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *OrganizationTokenResponse) GetDescription() string {
	if o == nil || isNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationTokenResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.Description) {
    return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *OrganizationTokenResponse) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *OrganizationTokenResponse) SetDescription(v string) {
	o.Description = &v
}

func (o OrganizationTokenResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.OrganizationId) {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if !isNil(o.AccessToken) {
		toSerialize["accessToken"] = o.AccessToken
	}
	if !isNil(o.TokenId) {
		toSerialize["tokenId"] = o.TokenId
	}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableOrganizationTokenResponse struct {
	value *OrganizationTokenResponse
	isSet bool
}

func (v NullableOrganizationTokenResponse) Get() *OrganizationTokenResponse {
	return v.value
}

func (v *NullableOrganizationTokenResponse) Set(val *OrganizationTokenResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationTokenResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationTokenResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationTokenResponse(val *OrganizationTokenResponse) *NullableOrganizationTokenResponse {
	return &NullableOrganizationTokenResponse{value: val, isSet: true}
}

func (v NullableOrganizationTokenResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationTokenResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


