/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RotateServiceTokenRequest struct for RotateServiceTokenRequest
type RotateServiceTokenRequest struct {
	ServiceId int64 `json:"serviceId"`
	OrganizationId int64 `json:"organizationId"`
	ApiServerId int64 `json:"apiServerId"`
	TokenId string `json:"tokenId"`
}

// NewRotateServiceTokenRequest instantiates a new RotateServiceTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRotateServiceTokenRequest(serviceId int64, organizationId int64, apiServerId int64, tokenId string) *RotateServiceTokenRequest {
	this := RotateServiceTokenRequest{}
	this.ServiceId = serviceId
	this.OrganizationId = organizationId
	this.ApiServerId = apiServerId
	this.TokenId = tokenId
	return &this
}

// NewRotateServiceTokenRequestWithDefaults instantiates a new RotateServiceTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRotateServiceTokenRequestWithDefaults() *RotateServiceTokenRequest {
	this := RotateServiceTokenRequest{}
	return &this
}

// GetServiceId returns the ServiceId field value
func (o *RotateServiceTokenRequest) GetServiceId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *RotateServiceTokenRequest) GetServiceIdOk() (*int64, bool) {
	if o == nil {
    return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *RotateServiceTokenRequest) SetServiceId(v int64) {
	o.ServiceId = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *RotateServiceTokenRequest) GetOrganizationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *RotateServiceTokenRequest) GetOrganizationIdOk() (*int64, bool) {
	if o == nil {
    return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *RotateServiceTokenRequest) SetOrganizationId(v int64) {
	o.OrganizationId = v
}

// GetApiServerId returns the ApiServerId field value
func (o *RotateServiceTokenRequest) GetApiServerId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ApiServerId
}

// GetApiServerIdOk returns a tuple with the ApiServerId field value
// and a boolean to check if the value has been set.
func (o *RotateServiceTokenRequest) GetApiServerIdOk() (*int64, bool) {
	if o == nil {
    return nil, false
	}
	return &o.ApiServerId, true
}

// SetApiServerId sets field value
func (o *RotateServiceTokenRequest) SetApiServerId(v int64) {
	o.ApiServerId = v
}

// GetTokenId returns the TokenId field value
func (o *RotateServiceTokenRequest) GetTokenId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value
// and a boolean to check if the value has been set.
func (o *RotateServiceTokenRequest) GetTokenIdOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.TokenId, true
}

// SetTokenId sets field value
func (o *RotateServiceTokenRequest) SetTokenId(v string) {
	o.TokenId = v
}

func (o RotateServiceTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["serviceId"] = o.ServiceId
	}
	if true {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if true {
		toSerialize["apiServerId"] = o.ApiServerId
	}
	if true {
		toSerialize["tokenId"] = o.TokenId
	}
	return json.Marshal(toSerialize)
}

type NullableRotateServiceTokenRequest struct {
	value *RotateServiceTokenRequest
	isSet bool
}

func (v NullableRotateServiceTokenRequest) Get() *RotateServiceTokenRequest {
	return v.value
}

func (v *NullableRotateServiceTokenRequest) Set(val *RotateServiceTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRotateServiceTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRotateServiceTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRotateServiceTokenRequest(val *RotateServiceTokenRequest) *NullableRotateServiceTokenRequest {
	return &NullableRotateServiceTokenRequest{value: val, isSet: true}
}

func (v NullableRotateServiceTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRotateServiceTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


