/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiServerMembershipResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiServerMembershipResponse{}

// ApiServerMembershipResponse struct for ApiServerMembershipResponse
type ApiServerMembershipResponse struct {
	ApiServerId *int64                              `json:"apiServerId,omitempty"`
	Url         *string                             `json:"url,omitempty"`
	Description *string                             `json:"description,omitempty"`
	Privileges  []string                            `json:"privileges,omitempty"`
	Services    []ServiceInstanceMembershipResponse `json:"services,omitempty"`
}

// NewApiServerMembershipResponse instantiates a new ApiServerMembershipResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiServerMembershipResponse() *ApiServerMembershipResponse {
	this := ApiServerMembershipResponse{}
	return &this
}

// NewApiServerMembershipResponseWithDefaults instantiates a new ApiServerMembershipResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiServerMembershipResponseWithDefaults() *ApiServerMembershipResponse {
	this := ApiServerMembershipResponse{}
	return &this
}

// GetApiServerId returns the ApiServerId field value if set, zero value otherwise.
func (o *ApiServerMembershipResponse) GetApiServerId() int64 {
	if o == nil || IsNil(o.ApiServerId) {
		var ret int64
		return ret
	}
	return *o.ApiServerId
}

// GetApiServerIdOk returns a tuple with the ApiServerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiServerMembershipResponse) GetApiServerIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ApiServerId) {
		return nil, false
	}
	return o.ApiServerId, true
}

// HasApiServerId returns a boolean if a field has been set.
func (o *ApiServerMembershipResponse) HasApiServerId() bool {
	if o != nil && !IsNil(o.ApiServerId) {
		return true
	}

	return false
}

// SetApiServerId gets a reference to the given int64 and assigns it to the ApiServerId field.
func (o *ApiServerMembershipResponse) SetApiServerId(v int64) {
	o.ApiServerId = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *ApiServerMembershipResponse) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiServerMembershipResponse) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *ApiServerMembershipResponse) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *ApiServerMembershipResponse) SetUrl(v string) {
	o.Url = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ApiServerMembershipResponse) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiServerMembershipResponse) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ApiServerMembershipResponse) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ApiServerMembershipResponse) SetDescription(v string) {
	o.Description = &v
}

// GetPrivileges returns the Privileges field value if set, zero value otherwise.
func (o *ApiServerMembershipResponse) GetPrivileges() []string {
	if o == nil || IsNil(o.Privileges) {
		var ret []string
		return ret
	}
	return o.Privileges
}

// GetPrivilegesOk returns a tuple with the Privileges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiServerMembershipResponse) GetPrivilegesOk() ([]string, bool) {
	if o == nil || IsNil(o.Privileges) {
		return nil, false
	}
	return o.Privileges, true
}

// HasPrivileges returns a boolean if a field has been set.
func (o *ApiServerMembershipResponse) HasPrivileges() bool {
	if o != nil && !IsNil(o.Privileges) {
		return true
	}

	return false
}

// SetPrivileges gets a reference to the given []string and assigns it to the Privileges field.
func (o *ApiServerMembershipResponse) SetPrivileges(v []string) {
	o.Privileges = v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *ApiServerMembershipResponse) GetServices() []ServiceInstanceMembershipResponse {
	if o == nil || IsNil(o.Services) {
		var ret []ServiceInstanceMembershipResponse
		return ret
	}
	return o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiServerMembershipResponse) GetServicesOk() ([]ServiceInstanceMembershipResponse, bool) {
	if o == nil || IsNil(o.Services) {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *ApiServerMembershipResponse) HasServices() bool {
	if o != nil && !IsNil(o.Services) {
		return true
	}

	return false
}

// SetServices gets a reference to the given []ServiceInstanceMembershipResponse and assigns it to the Services field.
func (o *ApiServerMembershipResponse) SetServices(v []ServiceInstanceMembershipResponse) {
	o.Services = v
}

func (o ApiServerMembershipResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiServerMembershipResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ApiServerId) {
		toSerialize["apiServerId"] = o.ApiServerId
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Privileges) {
		toSerialize["privileges"] = o.Privileges
	}
	if !IsNil(o.Services) {
		toSerialize["services"] = o.Services
	}
	return toSerialize, nil
}

type NullableApiServerMembershipResponse struct {
	value *ApiServerMembershipResponse
	isSet bool
}

func (v NullableApiServerMembershipResponse) Get() *ApiServerMembershipResponse {
	return v.value
}

func (v *NullableApiServerMembershipResponse) Set(val *ApiServerMembershipResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableApiServerMembershipResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableApiServerMembershipResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiServerMembershipResponse(val *ApiServerMembershipResponse) *NullableApiServerMembershipResponse {
	return &NullableApiServerMembershipResponse{value: val, isSet: true}
}

func (v NullableApiServerMembershipResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiServerMembershipResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
