/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the OrganizationAccessResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OrganizationAccessResponse{}

// OrganizationAccessResponse struct for OrganizationAccessResponse
type OrganizationAccessResponse struct {
	User                   *LogInResponse            `json:"user,omitempty"`
	UserId                 *int64                    `json:"userId,omitempty"`
	OrganizationId         *int64                    `json:"organizationId,omitempty"`
	Privileges             []string                  `json:"privileges,omitempty"`
	AllApiServerPrivileges []string                  `json:"allApiServerPrivileges,omitempty"`
	AllServicePrivileges   []string                  `json:"allServicePrivileges,omitempty"`
	AllClientPrivileges    []string                  `json:"allClientPrivileges,omitempty"`
	ApiServerAccess        []ApiServerAccessResponse `json:"apiServerAccess,omitempty"`
}

// NewOrganizationAccessResponse instantiates a new OrganizationAccessResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOrganizationAccessResponse() *OrganizationAccessResponse {
	this := OrganizationAccessResponse{}
	return &this
}

// NewOrganizationAccessResponseWithDefaults instantiates a new OrganizationAccessResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOrganizationAccessResponseWithDefaults() *OrganizationAccessResponse {
	this := OrganizationAccessResponse{}
	return &this
}

// GetUser returns the User field value if set, zero value otherwise.
func (o *OrganizationAccessResponse) GetUser() LogInResponse {
	if o == nil || IsNil(o.User) {
		var ret LogInResponse
		return ret
	}
	return *o.User
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAccessResponse) GetUserOk() (*LogInResponse, bool) {
	if o == nil || IsNil(o.User) {
		return nil, false
	}
	return o.User, true
}

// HasUser returns a boolean if a field has been set.
func (o *OrganizationAccessResponse) HasUser() bool {
	if o != nil && !IsNil(o.User) {
		return true
	}

	return false
}

// SetUser gets a reference to the given LogInResponse and assigns it to the User field.
func (o *OrganizationAccessResponse) SetUser(v LogInResponse) {
	o.User = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *OrganizationAccessResponse) GetUserId() int64 {
	if o == nil || IsNil(o.UserId) {
		var ret int64
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAccessResponse) GetUserIdOk() (*int64, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *OrganizationAccessResponse) HasUserId() bool {
	if o != nil && !IsNil(o.UserId) {
		return true
	}

	return false
}

// SetUserId gets a reference to the given int64 and assigns it to the UserId field.
func (o *OrganizationAccessResponse) SetUserId(v int64) {
	o.UserId = &v
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *OrganizationAccessResponse) GetOrganizationId() int64 {
	if o == nil || IsNil(o.OrganizationId) {
		var ret int64
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAccessResponse) GetOrganizationIdOk() (*int64, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *OrganizationAccessResponse) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given int64 and assigns it to the OrganizationId field.
func (o *OrganizationAccessResponse) SetOrganizationId(v int64) {
	o.OrganizationId = &v
}

// GetPrivileges returns the Privileges field value if set, zero value otherwise.
func (o *OrganizationAccessResponse) GetPrivileges() []string {
	if o == nil || IsNil(o.Privileges) {
		var ret []string
		return ret
	}
	return o.Privileges
}

// GetPrivilegesOk returns a tuple with the Privileges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAccessResponse) GetPrivilegesOk() ([]string, bool) {
	if o == nil || IsNil(o.Privileges) {
		return nil, false
	}
	return o.Privileges, true
}

// HasPrivileges returns a boolean if a field has been set.
func (o *OrganizationAccessResponse) HasPrivileges() bool {
	if o != nil && !IsNil(o.Privileges) {
		return true
	}

	return false
}

// SetPrivileges gets a reference to the given []string and assigns it to the Privileges field.
func (o *OrganizationAccessResponse) SetPrivileges(v []string) {
	o.Privileges = v
}

// GetAllApiServerPrivileges returns the AllApiServerPrivileges field value if set, zero value otherwise.
func (o *OrganizationAccessResponse) GetAllApiServerPrivileges() []string {
	if o == nil || IsNil(o.AllApiServerPrivileges) {
		var ret []string
		return ret
	}
	return o.AllApiServerPrivileges
}

// GetAllApiServerPrivilegesOk returns a tuple with the AllApiServerPrivileges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAccessResponse) GetAllApiServerPrivilegesOk() ([]string, bool) {
	if o == nil || IsNil(o.AllApiServerPrivileges) {
		return nil, false
	}
	return o.AllApiServerPrivileges, true
}

// HasAllApiServerPrivileges returns a boolean if a field has been set.
func (o *OrganizationAccessResponse) HasAllApiServerPrivileges() bool {
	if o != nil && !IsNil(o.AllApiServerPrivileges) {
		return true
	}

	return false
}

// SetAllApiServerPrivileges gets a reference to the given []string and assigns it to the AllApiServerPrivileges field.
func (o *OrganizationAccessResponse) SetAllApiServerPrivileges(v []string) {
	o.AllApiServerPrivileges = v
}

// GetAllServicePrivileges returns the AllServicePrivileges field value if set, zero value otherwise.
func (o *OrganizationAccessResponse) GetAllServicePrivileges() []string {
	if o == nil || IsNil(o.AllServicePrivileges) {
		var ret []string
		return ret
	}
	return o.AllServicePrivileges
}

// GetAllServicePrivilegesOk returns a tuple with the AllServicePrivileges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAccessResponse) GetAllServicePrivilegesOk() ([]string, bool) {
	if o == nil || IsNil(o.AllServicePrivileges) {
		return nil, false
	}
	return o.AllServicePrivileges, true
}

// HasAllServicePrivileges returns a boolean if a field has been set.
func (o *OrganizationAccessResponse) HasAllServicePrivileges() bool {
	if o != nil && !IsNil(o.AllServicePrivileges) {
		return true
	}

	return false
}

// SetAllServicePrivileges gets a reference to the given []string and assigns it to the AllServicePrivileges field.
func (o *OrganizationAccessResponse) SetAllServicePrivileges(v []string) {
	o.AllServicePrivileges = v
}

// GetAllClientPrivileges returns the AllClientPrivileges field value if set, zero value otherwise.
func (o *OrganizationAccessResponse) GetAllClientPrivileges() []string {
	if o == nil || IsNil(o.AllClientPrivileges) {
		var ret []string
		return ret
	}
	return o.AllClientPrivileges
}

// GetAllClientPrivilegesOk returns a tuple with the AllClientPrivileges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAccessResponse) GetAllClientPrivilegesOk() ([]string, bool) {
	if o == nil || IsNil(o.AllClientPrivileges) {
		return nil, false
	}
	return o.AllClientPrivileges, true
}

// HasAllClientPrivileges returns a boolean if a field has been set.
func (o *OrganizationAccessResponse) HasAllClientPrivileges() bool {
	if o != nil && !IsNil(o.AllClientPrivileges) {
		return true
	}

	return false
}

// SetAllClientPrivileges gets a reference to the given []string and assigns it to the AllClientPrivileges field.
func (o *OrganizationAccessResponse) SetAllClientPrivileges(v []string) {
	o.AllClientPrivileges = v
}

// GetApiServerAccess returns the ApiServerAccess field value if set, zero value otherwise.
func (o *OrganizationAccessResponse) GetApiServerAccess() []ApiServerAccessResponse {
	if o == nil || IsNil(o.ApiServerAccess) {
		var ret []ApiServerAccessResponse
		return ret
	}
	return o.ApiServerAccess
}

// GetApiServerAccessOk returns a tuple with the ApiServerAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OrganizationAccessResponse) GetApiServerAccessOk() ([]ApiServerAccessResponse, bool) {
	if o == nil || IsNil(o.ApiServerAccess) {
		return nil, false
	}
	return o.ApiServerAccess, true
}

// HasApiServerAccess returns a boolean if a field has been set.
func (o *OrganizationAccessResponse) HasApiServerAccess() bool {
	if o != nil && !IsNil(o.ApiServerAccess) {
		return true
	}

	return false
}

// SetApiServerAccess gets a reference to the given []ApiServerAccessResponse and assigns it to the ApiServerAccess field.
func (o *OrganizationAccessResponse) SetApiServerAccess(v []ApiServerAccessResponse) {
	o.ApiServerAccess = v
}

func (o OrganizationAccessResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OrganizationAccessResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.User) {
		toSerialize["user"] = o.User
	}
	if !IsNil(o.UserId) {
		toSerialize["userId"] = o.UserId
	}
	if !IsNil(o.OrganizationId) {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if !IsNil(o.Privileges) {
		toSerialize["privileges"] = o.Privileges
	}
	if !IsNil(o.AllApiServerPrivileges) {
		toSerialize["allApiServerPrivileges"] = o.AllApiServerPrivileges
	}
	if !IsNil(o.AllServicePrivileges) {
		toSerialize["allServicePrivileges"] = o.AllServicePrivileges
	}
	if !IsNil(o.AllClientPrivileges) {
		toSerialize["allClientPrivileges"] = o.AllClientPrivileges
	}
	if !IsNil(o.ApiServerAccess) {
		toSerialize["apiServerAccess"] = o.ApiServerAccess
	}
	return toSerialize, nil
}

type NullableOrganizationAccessResponse struct {
	value *OrganizationAccessResponse
	isSet bool
}

func (v NullableOrganizationAccessResponse) Get() *OrganizationAccessResponse {
	return v.value
}

func (v *NullableOrganizationAccessResponse) Set(val *OrganizationAccessResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableOrganizationAccessResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableOrganizationAccessResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOrganizationAccessResponse(val *OrganizationAccessResponse) *NullableOrganizationAccessResponse {
	return &NullableOrganizationAccessResponse{value: val, isSet: true}
}

func (v NullableOrganizationAccessResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOrganizationAccessResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
