/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CredentialIssuerMetadata struct for CredentialIssuerMetadata
type CredentialIssuerMetadata struct {
	CredentialIssuer *string `json:"credentialIssuer,omitempty"`
	AuthorizationServer *string `json:"authorizationServer,omitempty"`
	CredentialEndpoint *string `json:"credentialEndpoint,omitempty"`
	BatchCredentialEndpoint *string `json:"batchCredentialEndpoint,omitempty"`
	DeferredCredentialEndpoint *string `json:"deferredCredentialEndpoint,omitempty"`
	CredentialsSupported *string `json:"credentialsSupported,omitempty"`
	Empty *bool `json:"empty,omitempty"`
}

// NewCredentialIssuerMetadata instantiates a new CredentialIssuerMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCredentialIssuerMetadata() *CredentialIssuerMetadata {
	this := CredentialIssuerMetadata{}
	return &this
}

// NewCredentialIssuerMetadataWithDefaults instantiates a new CredentialIssuerMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCredentialIssuerMetadataWithDefaults() *CredentialIssuerMetadata {
	this := CredentialIssuerMetadata{}
	return &this
}

// GetCredentialIssuer returns the CredentialIssuer field value if set, zero value otherwise.
func (o *CredentialIssuerMetadata) GetCredentialIssuer() string {
	if o == nil || isNil(o.CredentialIssuer) {
		var ret string
		return ret
	}
	return *o.CredentialIssuer
}

// GetCredentialIssuerOk returns a tuple with the CredentialIssuer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialIssuerMetadata) GetCredentialIssuerOk() (*string, bool) {
	if o == nil || isNil(o.CredentialIssuer) {
    return nil, false
	}
	return o.CredentialIssuer, true
}

// HasCredentialIssuer returns a boolean if a field has been set.
func (o *CredentialIssuerMetadata) HasCredentialIssuer() bool {
	if o != nil && !isNil(o.CredentialIssuer) {
		return true
	}

	return false
}

// SetCredentialIssuer gets a reference to the given string and assigns it to the CredentialIssuer field.
func (o *CredentialIssuerMetadata) SetCredentialIssuer(v string) {
	o.CredentialIssuer = &v
}

// GetAuthorizationServer returns the AuthorizationServer field value if set, zero value otherwise.
func (o *CredentialIssuerMetadata) GetAuthorizationServer() string {
	if o == nil || isNil(o.AuthorizationServer) {
		var ret string
		return ret
	}
	return *o.AuthorizationServer
}

// GetAuthorizationServerOk returns a tuple with the AuthorizationServer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialIssuerMetadata) GetAuthorizationServerOk() (*string, bool) {
	if o == nil || isNil(o.AuthorizationServer) {
    return nil, false
	}
	return o.AuthorizationServer, true
}

// HasAuthorizationServer returns a boolean if a field has been set.
func (o *CredentialIssuerMetadata) HasAuthorizationServer() bool {
	if o != nil && !isNil(o.AuthorizationServer) {
		return true
	}

	return false
}

// SetAuthorizationServer gets a reference to the given string and assigns it to the AuthorizationServer field.
func (o *CredentialIssuerMetadata) SetAuthorizationServer(v string) {
	o.AuthorizationServer = &v
}

// GetCredentialEndpoint returns the CredentialEndpoint field value if set, zero value otherwise.
func (o *CredentialIssuerMetadata) GetCredentialEndpoint() string {
	if o == nil || isNil(o.CredentialEndpoint) {
		var ret string
		return ret
	}
	return *o.CredentialEndpoint
}

// GetCredentialEndpointOk returns a tuple with the CredentialEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialIssuerMetadata) GetCredentialEndpointOk() (*string, bool) {
	if o == nil || isNil(o.CredentialEndpoint) {
    return nil, false
	}
	return o.CredentialEndpoint, true
}

// HasCredentialEndpoint returns a boolean if a field has been set.
func (o *CredentialIssuerMetadata) HasCredentialEndpoint() bool {
	if o != nil && !isNil(o.CredentialEndpoint) {
		return true
	}

	return false
}

// SetCredentialEndpoint gets a reference to the given string and assigns it to the CredentialEndpoint field.
func (o *CredentialIssuerMetadata) SetCredentialEndpoint(v string) {
	o.CredentialEndpoint = &v
}

// GetBatchCredentialEndpoint returns the BatchCredentialEndpoint field value if set, zero value otherwise.
func (o *CredentialIssuerMetadata) GetBatchCredentialEndpoint() string {
	if o == nil || isNil(o.BatchCredentialEndpoint) {
		var ret string
		return ret
	}
	return *o.BatchCredentialEndpoint
}

// GetBatchCredentialEndpointOk returns a tuple with the BatchCredentialEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialIssuerMetadata) GetBatchCredentialEndpointOk() (*string, bool) {
	if o == nil || isNil(o.BatchCredentialEndpoint) {
    return nil, false
	}
	return o.BatchCredentialEndpoint, true
}

// HasBatchCredentialEndpoint returns a boolean if a field has been set.
func (o *CredentialIssuerMetadata) HasBatchCredentialEndpoint() bool {
	if o != nil && !isNil(o.BatchCredentialEndpoint) {
		return true
	}

	return false
}

// SetBatchCredentialEndpoint gets a reference to the given string and assigns it to the BatchCredentialEndpoint field.
func (o *CredentialIssuerMetadata) SetBatchCredentialEndpoint(v string) {
	o.BatchCredentialEndpoint = &v
}

// GetDeferredCredentialEndpoint returns the DeferredCredentialEndpoint field value if set, zero value otherwise.
func (o *CredentialIssuerMetadata) GetDeferredCredentialEndpoint() string {
	if o == nil || isNil(o.DeferredCredentialEndpoint) {
		var ret string
		return ret
	}
	return *o.DeferredCredentialEndpoint
}

// GetDeferredCredentialEndpointOk returns a tuple with the DeferredCredentialEndpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialIssuerMetadata) GetDeferredCredentialEndpointOk() (*string, bool) {
	if o == nil || isNil(o.DeferredCredentialEndpoint) {
    return nil, false
	}
	return o.DeferredCredentialEndpoint, true
}

// HasDeferredCredentialEndpoint returns a boolean if a field has been set.
func (o *CredentialIssuerMetadata) HasDeferredCredentialEndpoint() bool {
	if o != nil && !isNil(o.DeferredCredentialEndpoint) {
		return true
	}

	return false
}

// SetDeferredCredentialEndpoint gets a reference to the given string and assigns it to the DeferredCredentialEndpoint field.
func (o *CredentialIssuerMetadata) SetDeferredCredentialEndpoint(v string) {
	o.DeferredCredentialEndpoint = &v
}

// GetCredentialsSupported returns the CredentialsSupported field value if set, zero value otherwise.
func (o *CredentialIssuerMetadata) GetCredentialsSupported() string {
	if o == nil || isNil(o.CredentialsSupported) {
		var ret string
		return ret
	}
	return *o.CredentialsSupported
}

// GetCredentialsSupportedOk returns a tuple with the CredentialsSupported field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialIssuerMetadata) GetCredentialsSupportedOk() (*string, bool) {
	if o == nil || isNil(o.CredentialsSupported) {
    return nil, false
	}
	return o.CredentialsSupported, true
}

// HasCredentialsSupported returns a boolean if a field has been set.
func (o *CredentialIssuerMetadata) HasCredentialsSupported() bool {
	if o != nil && !isNil(o.CredentialsSupported) {
		return true
	}

	return false
}

// SetCredentialsSupported gets a reference to the given string and assigns it to the CredentialsSupported field.
func (o *CredentialIssuerMetadata) SetCredentialsSupported(v string) {
	o.CredentialsSupported = &v
}

// GetEmpty returns the Empty field value if set, zero value otherwise.
func (o *CredentialIssuerMetadata) GetEmpty() bool {
	if o == nil || isNil(o.Empty) {
		var ret bool
		return ret
	}
	return *o.Empty
}

// GetEmptyOk returns a tuple with the Empty field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CredentialIssuerMetadata) GetEmptyOk() (*bool, bool) {
	if o == nil || isNil(o.Empty) {
    return nil, false
	}
	return o.Empty, true
}

// HasEmpty returns a boolean if a field has been set.
func (o *CredentialIssuerMetadata) HasEmpty() bool {
	if o != nil && !isNil(o.Empty) {
		return true
	}

	return false
}

// SetEmpty gets a reference to the given bool and assigns it to the Empty field.
func (o *CredentialIssuerMetadata) SetEmpty(v bool) {
	o.Empty = &v
}

func (o CredentialIssuerMetadata) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.CredentialIssuer) {
		toSerialize["credentialIssuer"] = o.CredentialIssuer
	}
	if !isNil(o.AuthorizationServer) {
		toSerialize["authorizationServer"] = o.AuthorizationServer
	}
	if !isNil(o.CredentialEndpoint) {
		toSerialize["credentialEndpoint"] = o.CredentialEndpoint
	}
	if !isNil(o.BatchCredentialEndpoint) {
		toSerialize["batchCredentialEndpoint"] = o.BatchCredentialEndpoint
	}
	if !isNil(o.DeferredCredentialEndpoint) {
		toSerialize["deferredCredentialEndpoint"] = o.DeferredCredentialEndpoint
	}
	if !isNil(o.CredentialsSupported) {
		toSerialize["credentialsSupported"] = o.CredentialsSupported
	}
	if !isNil(o.Empty) {
		toSerialize["empty"] = o.Empty
	}
	return json.Marshal(toSerialize)
}

type NullableCredentialIssuerMetadata struct {
	value *CredentialIssuerMetadata
	isSet bool
}

func (v NullableCredentialIssuerMetadata) Get() *CredentialIssuerMetadata {
	return v.value
}

func (v *NullableCredentialIssuerMetadata) Set(val *CredentialIssuerMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableCredentialIssuerMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableCredentialIssuerMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCredentialIssuerMetadata(val *CredentialIssuerMetadata) *NullableCredentialIssuerMetadata {
	return &NullableCredentialIssuerMetadata{value: val, isSet: true}
}

func (v NullableCredentialIssuerMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCredentialIssuerMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


