/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the DeleteServiceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeleteServiceRequest{}

// DeleteServiceRequest struct for DeleteServiceRequest
type DeleteServiceRequest struct {
	ApiServerId    int64 `json:"apiServerId"`
	OrganizationId int64 `json:"organizationId"`
	ServiceId      int64 `json:"serviceId"`
}

type _DeleteServiceRequest DeleteServiceRequest

// NewDeleteServiceRequest instantiates a new DeleteServiceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeleteServiceRequest(apiServerId int64, organizationId int64, serviceId int64) *DeleteServiceRequest {
	this := DeleteServiceRequest{}
	this.ApiServerId = apiServerId
	this.OrganizationId = organizationId
	this.ServiceId = serviceId
	return &this
}

// NewDeleteServiceRequestWithDefaults instantiates a new DeleteServiceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeleteServiceRequestWithDefaults() *DeleteServiceRequest {
	this := DeleteServiceRequest{}
	return &this
}

// GetApiServerId returns the ApiServerId field value
func (o *DeleteServiceRequest) GetApiServerId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ApiServerId
}

// GetApiServerIdOk returns a tuple with the ApiServerId field value
// and a boolean to check if the value has been set.
func (o *DeleteServiceRequest) GetApiServerIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiServerId, true
}

// SetApiServerId sets field value
func (o *DeleteServiceRequest) SetApiServerId(v int64) {
	o.ApiServerId = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *DeleteServiceRequest) GetOrganizationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *DeleteServiceRequest) GetOrganizationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *DeleteServiceRequest) SetOrganizationId(v int64) {
	o.OrganizationId = v
}

// GetServiceId returns the ServiceId field value
func (o *DeleteServiceRequest) GetServiceId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *DeleteServiceRequest) GetServiceIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *DeleteServiceRequest) SetServiceId(v int64) {
	o.ServiceId = v
}

func (o DeleteServiceRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeleteServiceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["apiServerId"] = o.ApiServerId
	toSerialize["organizationId"] = o.OrganizationId
	toSerialize["serviceId"] = o.ServiceId
	return toSerialize, nil
}

func (o *DeleteServiceRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"apiServerId",
		"organizationId",
		"serviceId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeleteServiceRequest := _DeleteServiceRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeleteServiceRequest)

	if err != nil {
		return err
	}

	*o = DeleteServiceRequest(varDeleteServiceRequest)

	return err
}

type NullableDeleteServiceRequest struct {
	value *DeleteServiceRequest
	isSet bool
}

func (v NullableDeleteServiceRequest) Get() *DeleteServiceRequest {
	return v.value
}

func (v *NullableDeleteServiceRequest) Set(val *DeleteServiceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDeleteServiceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDeleteServiceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeleteServiceRequest(val *DeleteServiceRequest) *NullableDeleteServiceRequest {
	return &NullableDeleteServiceRequest{value: val, isSet: true}
}

func (v NullableDeleteServiceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeleteServiceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
