/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// CreateOrganizationTokenRequest struct for CreateOrganizationTokenRequest
type CreateOrganizationTokenRequest struct {
	OrganizationId int64 `json:"organizationId"`
	Description string `json:"description"`
}

// NewCreateOrganizationTokenRequest instantiates a new CreateOrganizationTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrganizationTokenRequest(organizationId int64, description string) *CreateOrganizationTokenRequest {
	this := CreateOrganizationTokenRequest{}
	this.OrganizationId = organizationId
	this.Description = description
	return &this
}

// NewCreateOrganizationTokenRequestWithDefaults instantiates a new CreateOrganizationTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrganizationTokenRequestWithDefaults() *CreateOrganizationTokenRequest {
	this := CreateOrganizationTokenRequest{}
	return &this
}

// GetOrganizationId returns the OrganizationId field value
func (o *CreateOrganizationTokenRequest) GetOrganizationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *CreateOrganizationTokenRequest) GetOrganizationIdOk() (*int64, bool) {
	if o == nil {
    return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *CreateOrganizationTokenRequest) SetOrganizationId(v int64) {
	o.OrganizationId = v
}

// GetDescription returns the Description field value
func (o *CreateOrganizationTokenRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CreateOrganizationTokenRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CreateOrganizationTokenRequest) SetDescription(v string) {
	o.Description = v
}

func (o CreateOrganizationTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if true {
		toSerialize["description"] = o.Description
	}
	return json.Marshal(toSerialize)
}

type NullableCreateOrganizationTokenRequest struct {
	value *CreateOrganizationTokenRequest
	isSet bool
}

func (v NullableCreateOrganizationTokenRequest) Get() *CreateOrganizationTokenRequest {
	return v.value
}

func (v *NullableCreateOrganizationTokenRequest) Set(val *CreateOrganizationTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrganizationTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrganizationTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrganizationTokenRequest(val *CreateOrganizationTokenRequest) *NullableCreateOrganizationTokenRequest {
	return &NullableCreateOrganizationTokenRequest{value: val, isSet: true}
}

func (v NullableCreateOrganizationTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrganizationTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


