/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InviteRequest struct for InviteRequest
type InviteRequest struct {
	OrganizationId int64 `json:"organizationId"`
	Email string `json:"email"`
	OrganizationPrivileges []string `json:"organizationPrivileges,omitempty"`
	ApiServerPrivileges []string `json:"apiServerPrivileges,omitempty"`
	ServicePrivileges []string `json:"servicePrivileges,omitempty"`
	ClientPrivileges []string `json:"clientPrivileges,omitempty"`
}

// NewInviteRequest instantiates a new InviteRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInviteRequest(organizationId int64, email string) *InviteRequest {
	this := InviteRequest{}
	this.OrganizationId = organizationId
	this.Email = email
	return &this
}

// NewInviteRequestWithDefaults instantiates a new InviteRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInviteRequestWithDefaults() *InviteRequest {
	this := InviteRequest{}
	return &this
}

// GetOrganizationId returns the OrganizationId field value
func (o *InviteRequest) GetOrganizationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *InviteRequest) GetOrganizationIdOk() (*int64, bool) {
	if o == nil {
    return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *InviteRequest) SetOrganizationId(v int64) {
	o.OrganizationId = v
}

// GetEmail returns the Email field value
func (o *InviteRequest) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *InviteRequest) GetEmailOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *InviteRequest) SetEmail(v string) {
	o.Email = v
}

// GetOrganizationPrivileges returns the OrganizationPrivileges field value if set, zero value otherwise.
func (o *InviteRequest) GetOrganizationPrivileges() []string {
	if o == nil || isNil(o.OrganizationPrivileges) {
		var ret []string
		return ret
	}
	return o.OrganizationPrivileges
}

// GetOrganizationPrivilegesOk returns a tuple with the OrganizationPrivileges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InviteRequest) GetOrganizationPrivilegesOk() ([]string, bool) {
	if o == nil || isNil(o.OrganizationPrivileges) {
    return nil, false
	}
	return o.OrganizationPrivileges, true
}

// HasOrganizationPrivileges returns a boolean if a field has been set.
func (o *InviteRequest) HasOrganizationPrivileges() bool {
	if o != nil && !isNil(o.OrganizationPrivileges) {
		return true
	}

	return false
}

// SetOrganizationPrivileges gets a reference to the given []string and assigns it to the OrganizationPrivileges field.
func (o *InviteRequest) SetOrganizationPrivileges(v []string) {
	o.OrganizationPrivileges = v
}

// GetApiServerPrivileges returns the ApiServerPrivileges field value if set, zero value otherwise.
func (o *InviteRequest) GetApiServerPrivileges() []string {
	if o == nil || isNil(o.ApiServerPrivileges) {
		var ret []string
		return ret
	}
	return o.ApiServerPrivileges
}

// GetApiServerPrivilegesOk returns a tuple with the ApiServerPrivileges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InviteRequest) GetApiServerPrivilegesOk() ([]string, bool) {
	if o == nil || isNil(o.ApiServerPrivileges) {
    return nil, false
	}
	return o.ApiServerPrivileges, true
}

// HasApiServerPrivileges returns a boolean if a field has been set.
func (o *InviteRequest) HasApiServerPrivileges() bool {
	if o != nil && !isNil(o.ApiServerPrivileges) {
		return true
	}

	return false
}

// SetApiServerPrivileges gets a reference to the given []string and assigns it to the ApiServerPrivileges field.
func (o *InviteRequest) SetApiServerPrivileges(v []string) {
	o.ApiServerPrivileges = v
}

// GetServicePrivileges returns the ServicePrivileges field value if set, zero value otherwise.
func (o *InviteRequest) GetServicePrivileges() []string {
	if o == nil || isNil(o.ServicePrivileges) {
		var ret []string
		return ret
	}
	return o.ServicePrivileges
}

// GetServicePrivilegesOk returns a tuple with the ServicePrivileges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InviteRequest) GetServicePrivilegesOk() ([]string, bool) {
	if o == nil || isNil(o.ServicePrivileges) {
    return nil, false
	}
	return o.ServicePrivileges, true
}

// HasServicePrivileges returns a boolean if a field has been set.
func (o *InviteRequest) HasServicePrivileges() bool {
	if o != nil && !isNil(o.ServicePrivileges) {
		return true
	}

	return false
}

// SetServicePrivileges gets a reference to the given []string and assigns it to the ServicePrivileges field.
func (o *InviteRequest) SetServicePrivileges(v []string) {
	o.ServicePrivileges = v
}

// GetClientPrivileges returns the ClientPrivileges field value if set, zero value otherwise.
func (o *InviteRequest) GetClientPrivileges() []string {
	if o == nil || isNil(o.ClientPrivileges) {
		var ret []string
		return ret
	}
	return o.ClientPrivileges
}

// GetClientPrivilegesOk returns a tuple with the ClientPrivileges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InviteRequest) GetClientPrivilegesOk() ([]string, bool) {
	if o == nil || isNil(o.ClientPrivileges) {
    return nil, false
	}
	return o.ClientPrivileges, true
}

// HasClientPrivileges returns a boolean if a field has been set.
func (o *InviteRequest) HasClientPrivileges() bool {
	if o != nil && !isNil(o.ClientPrivileges) {
		return true
	}

	return false
}

// SetClientPrivileges gets a reference to the given []string and assigns it to the ClientPrivileges field.
func (o *InviteRequest) SetClientPrivileges(v []string) {
	o.ClientPrivileges = v
}

func (o InviteRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if true {
		toSerialize["email"] = o.Email
	}
	if !isNil(o.OrganizationPrivileges) {
		toSerialize["organizationPrivileges"] = o.OrganizationPrivileges
	}
	if !isNil(o.ApiServerPrivileges) {
		toSerialize["apiServerPrivileges"] = o.ApiServerPrivileges
	}
	if !isNil(o.ServicePrivileges) {
		toSerialize["servicePrivileges"] = o.ServicePrivileges
	}
	if !isNil(o.ClientPrivileges) {
		toSerialize["clientPrivileges"] = o.ClientPrivileges
	}
	return json.Marshal(toSerialize)
}

type NullableInviteRequest struct {
	value *InviteRequest
	isSet bool
}

func (v NullableInviteRequest) Get() *InviteRequest {
	return v.value
}

func (v *NullableInviteRequest) Set(val *InviteRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteRequest(val *InviteRequest) *NullableInviteRequest {
	return &NullableInviteRequest{value: val, isSet: true}
}

func (v NullableInviteRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


