/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// RotateOrganizationTokenRequest struct for RotateOrganizationTokenRequest
type RotateOrganizationTokenRequest struct {
	OrganizationId int64 `json:"organizationId"`
	TokenId string `json:"tokenId"`
}

// NewRotateOrganizationTokenRequest instantiates a new RotateOrganizationTokenRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRotateOrganizationTokenRequest(organizationId int64, tokenId string) *RotateOrganizationTokenRequest {
	this := RotateOrganizationTokenRequest{}
	this.OrganizationId = organizationId
	this.TokenId = tokenId
	return &this
}

// NewRotateOrganizationTokenRequestWithDefaults instantiates a new RotateOrganizationTokenRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRotateOrganizationTokenRequestWithDefaults() *RotateOrganizationTokenRequest {
	this := RotateOrganizationTokenRequest{}
	return &this
}

// GetOrganizationId returns the OrganizationId field value
func (o *RotateOrganizationTokenRequest) GetOrganizationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *RotateOrganizationTokenRequest) GetOrganizationIdOk() (*int64, bool) {
	if o == nil {
    return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *RotateOrganizationTokenRequest) SetOrganizationId(v int64) {
	o.OrganizationId = v
}

// GetTokenId returns the TokenId field value
func (o *RotateOrganizationTokenRequest) GetTokenId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value
// and a boolean to check if the value has been set.
func (o *RotateOrganizationTokenRequest) GetTokenIdOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.TokenId, true
}

// SetTokenId sets field value
func (o *RotateOrganizationTokenRequest) SetTokenId(v string) {
	o.TokenId = v
}

func (o RotateOrganizationTokenRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if true {
		toSerialize["tokenId"] = o.TokenId
	}
	return json.Marshal(toSerialize)
}

type NullableRotateOrganizationTokenRequest struct {
	value *RotateOrganizationTokenRequest
	isSet bool
}

func (v NullableRotateOrganizationTokenRequest) Get() *RotateOrganizationTokenRequest {
	return v.value
}

func (v *NullableRotateOrganizationTokenRequest) Set(val *RotateOrganizationTokenRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRotateOrganizationTokenRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRotateOrganizationTokenRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRotateOrganizationTokenRequest(val *RotateOrganizationTokenRequest) *NullableRotateOrganizationTokenRequest {
	return &NullableRotateOrganizationTokenRequest{value: val, isSet: true}
}

func (v NullableRotateOrganizationTokenRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRotateOrganizationTokenRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


