/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the UpdateClientPrivilegesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateClientPrivilegesRequest{}

// UpdateClientPrivilegesRequest struct for UpdateClientPrivilegesRequest
type UpdateClientPrivilegesRequest struct {
	ApiServerId    int64    `json:"apiServerId"`
	OrganizationId int64    `json:"organizationId"`
	UserId         int64    `json:"userId"`
	ServiceId      int64    `json:"serviceId"`
	ClientId       int64    `json:"clientId"`
	Privileges     []string `json:"privileges,omitempty"`
}

type _UpdateClientPrivilegesRequest UpdateClientPrivilegesRequest

// NewUpdateClientPrivilegesRequest instantiates a new UpdateClientPrivilegesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateClientPrivilegesRequest(apiServerId int64, organizationId int64, userId int64, serviceId int64, clientId int64) *UpdateClientPrivilegesRequest {
	this := UpdateClientPrivilegesRequest{}
	this.ApiServerId = apiServerId
	this.OrganizationId = organizationId
	this.UserId = userId
	this.ServiceId = serviceId
	this.ClientId = clientId
	return &this
}

// NewUpdateClientPrivilegesRequestWithDefaults instantiates a new UpdateClientPrivilegesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateClientPrivilegesRequestWithDefaults() *UpdateClientPrivilegesRequest {
	this := UpdateClientPrivilegesRequest{}
	return &this
}

// GetApiServerId returns the ApiServerId field value
func (o *UpdateClientPrivilegesRequest) GetApiServerId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ApiServerId
}

// GetApiServerIdOk returns a tuple with the ApiServerId field value
// and a boolean to check if the value has been set.
func (o *UpdateClientPrivilegesRequest) GetApiServerIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiServerId, true
}

// SetApiServerId sets field value
func (o *UpdateClientPrivilegesRequest) SetApiServerId(v int64) {
	o.ApiServerId = v
}

// GetOrganizationId returns the OrganizationId field value
func (o *UpdateClientPrivilegesRequest) GetOrganizationId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value
// and a boolean to check if the value has been set.
func (o *UpdateClientPrivilegesRequest) GetOrganizationIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.OrganizationId, true
}

// SetOrganizationId sets field value
func (o *UpdateClientPrivilegesRequest) SetOrganizationId(v int64) {
	o.OrganizationId = v
}

// GetUserId returns the UserId field value
func (o *UpdateClientPrivilegesRequest) GetUserId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *UpdateClientPrivilegesRequest) GetUserIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *UpdateClientPrivilegesRequest) SetUserId(v int64) {
	o.UserId = v
}

// GetServiceId returns the ServiceId field value
func (o *UpdateClientPrivilegesRequest) GetServiceId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value
// and a boolean to check if the value has been set.
func (o *UpdateClientPrivilegesRequest) GetServiceIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ServiceId, true
}

// SetServiceId sets field value
func (o *UpdateClientPrivilegesRequest) SetServiceId(v int64) {
	o.ServiceId = v
}

// GetClientId returns the ClientId field value
func (o *UpdateClientPrivilegesRequest) GetClientId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.ClientId
}

// GetClientIdOk returns a tuple with the ClientId field value
// and a boolean to check if the value has been set.
func (o *UpdateClientPrivilegesRequest) GetClientIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ClientId, true
}

// SetClientId sets field value
func (o *UpdateClientPrivilegesRequest) SetClientId(v int64) {
	o.ClientId = v
}

// GetPrivileges returns the Privileges field value if set, zero value otherwise.
func (o *UpdateClientPrivilegesRequest) GetPrivileges() []string {
	if o == nil || IsNil(o.Privileges) {
		var ret []string
		return ret
	}
	return o.Privileges
}

// GetPrivilegesOk returns a tuple with the Privileges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateClientPrivilegesRequest) GetPrivilegesOk() ([]string, bool) {
	if o == nil || IsNil(o.Privileges) {
		return nil, false
	}
	return o.Privileges, true
}

// HasPrivileges returns a boolean if a field has been set.
func (o *UpdateClientPrivilegesRequest) HasPrivileges() bool {
	if o != nil && !IsNil(o.Privileges) {
		return true
	}

	return false
}

// SetPrivileges gets a reference to the given []string and assigns it to the Privileges field.
func (o *UpdateClientPrivilegesRequest) SetPrivileges(v []string) {
	o.Privileges = v
}

func (o UpdateClientPrivilegesRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateClientPrivilegesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["apiServerId"] = o.ApiServerId
	toSerialize["organizationId"] = o.OrganizationId
	toSerialize["userId"] = o.UserId
	toSerialize["serviceId"] = o.ServiceId
	toSerialize["clientId"] = o.ClientId
	if !IsNil(o.Privileges) {
		toSerialize["privileges"] = o.Privileges
	}
	return toSerialize, nil
}

func (o *UpdateClientPrivilegesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"apiServerId",
		"organizationId",
		"userId",
		"serviceId",
		"clientId",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateClientPrivilegesRequest := _UpdateClientPrivilegesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateClientPrivilegesRequest)

	if err != nil {
		return err
	}

	*o = UpdateClientPrivilegesRequest(varUpdateClientPrivilegesRequest)

	return err
}

type NullableUpdateClientPrivilegesRequest struct {
	value *UpdateClientPrivilegesRequest
	isSet bool
}

func (v NullableUpdateClientPrivilegesRequest) Get() *UpdateClientPrivilegesRequest {
	return v.value
}

func (v *NullableUpdateClientPrivilegesRequest) Set(val *UpdateClientPrivilegesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateClientPrivilegesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateClientPrivilegesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateClientPrivilegesRequest(val *UpdateClientPrivilegesRequest) *NullableUpdateClientPrivilegesRequest {
	return &NullableUpdateClientPrivilegesRequest{value: val, isSet: true}
}

func (v NullableUpdateClientPrivilegesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateClientPrivilegesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
