/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServiceInstanceManagementResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServiceInstanceManagementResponse{}

// ServiceInstanceManagementResponse struct for ServiceInstanceManagementResponse
type ServiceInstanceManagementResponse struct {
	OrganizationId *int64 `json:"organizationId,omitempty"`
	ApiServerId    *int64 `json:"apiServerId,omitempty"`
	ServiceId      *int64 `json:"serviceId,omitempty"`
}

// NewServiceInstanceManagementResponse instantiates a new ServiceInstanceManagementResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServiceInstanceManagementResponse() *ServiceInstanceManagementResponse {
	this := ServiceInstanceManagementResponse{}
	return &this
}

// NewServiceInstanceManagementResponseWithDefaults instantiates a new ServiceInstanceManagementResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServiceInstanceManagementResponseWithDefaults() *ServiceInstanceManagementResponse {
	this := ServiceInstanceManagementResponse{}
	return &this
}

// GetOrganizationId returns the OrganizationId field value if set, zero value otherwise.
func (o *ServiceInstanceManagementResponse) GetOrganizationId() int64 {
	if o == nil || IsNil(o.OrganizationId) {
		var ret int64
		return ret
	}
	return *o.OrganizationId
}

// GetOrganizationIdOk returns a tuple with the OrganizationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceInstanceManagementResponse) GetOrganizationIdOk() (*int64, bool) {
	if o == nil || IsNil(o.OrganizationId) {
		return nil, false
	}
	return o.OrganizationId, true
}

// HasOrganizationId returns a boolean if a field has been set.
func (o *ServiceInstanceManagementResponse) HasOrganizationId() bool {
	if o != nil && !IsNil(o.OrganizationId) {
		return true
	}

	return false
}

// SetOrganizationId gets a reference to the given int64 and assigns it to the OrganizationId field.
func (o *ServiceInstanceManagementResponse) SetOrganizationId(v int64) {
	o.OrganizationId = &v
}

// GetApiServerId returns the ApiServerId field value if set, zero value otherwise.
func (o *ServiceInstanceManagementResponse) GetApiServerId() int64 {
	if o == nil || IsNil(o.ApiServerId) {
		var ret int64
		return ret
	}
	return *o.ApiServerId
}

// GetApiServerIdOk returns a tuple with the ApiServerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceInstanceManagementResponse) GetApiServerIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ApiServerId) {
		return nil, false
	}
	return o.ApiServerId, true
}

// HasApiServerId returns a boolean if a field has been set.
func (o *ServiceInstanceManagementResponse) HasApiServerId() bool {
	if o != nil && !IsNil(o.ApiServerId) {
		return true
	}

	return false
}

// SetApiServerId gets a reference to the given int64 and assigns it to the ApiServerId field.
func (o *ServiceInstanceManagementResponse) SetApiServerId(v int64) {
	o.ApiServerId = &v
}

// GetServiceId returns the ServiceId field value if set, zero value otherwise.
func (o *ServiceInstanceManagementResponse) GetServiceId() int64 {
	if o == nil || IsNil(o.ServiceId) {
		var ret int64
		return ret
	}
	return *o.ServiceId
}

// GetServiceIdOk returns a tuple with the ServiceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServiceInstanceManagementResponse) GetServiceIdOk() (*int64, bool) {
	if o == nil || IsNil(o.ServiceId) {
		return nil, false
	}
	return o.ServiceId, true
}

// HasServiceId returns a boolean if a field has been set.
func (o *ServiceInstanceManagementResponse) HasServiceId() bool {
	if o != nil && !IsNil(o.ServiceId) {
		return true
	}

	return false
}

// SetServiceId gets a reference to the given int64 and assigns it to the ServiceId field.
func (o *ServiceInstanceManagementResponse) SetServiceId(v int64) {
	o.ServiceId = &v
}

func (o ServiceInstanceManagementResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServiceInstanceManagementResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.OrganizationId) {
		toSerialize["organizationId"] = o.OrganizationId
	}
	if !IsNil(o.ApiServerId) {
		toSerialize["apiServerId"] = o.ApiServerId
	}
	if !IsNil(o.ServiceId) {
		toSerialize["serviceId"] = o.ServiceId
	}
	return toSerialize, nil
}

type NullableServiceInstanceManagementResponse struct {
	value *ServiceInstanceManagementResponse
	isSet bool
}

func (v NullableServiceInstanceManagementResponse) Get() *ServiceInstanceManagementResponse {
	return v.value
}

func (v *NullableServiceInstanceManagementResponse) Set(val *ServiceInstanceManagementResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableServiceInstanceManagementResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableServiceInstanceManagementResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServiceInstanceManagementResponse(val *ServiceInstanceManagementResponse) *NullableServiceInstanceManagementResponse {
	return &NullableServiceInstanceManagementResponse{value: val, isSet: true}
}

func (v NullableServiceInstanceManagementResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServiceInstanceManagementResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
