/*
OpenAPI definition

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: v0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the CreateApiServerRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateApiServerRequest{}

// CreateApiServerRequest struct for CreateApiServerRequest
type CreateApiServerRequest struct {
	ApiServerUrl string `json:"apiServerUrl"`
	Description  string `json:"description"`
	OwnedBy      *int64 `json:"ownedBy,omitempty"`
}

type _CreateApiServerRequest CreateApiServerRequest

// NewCreateApiServerRequest instantiates a new CreateApiServerRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateApiServerRequest(apiServerUrl string, description string) *CreateApiServerRequest {
	this := CreateApiServerRequest{}
	this.ApiServerUrl = apiServerUrl
	this.Description = description
	return &this
}

// NewCreateApiServerRequestWithDefaults instantiates a new CreateApiServerRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateApiServerRequestWithDefaults() *CreateApiServerRequest {
	this := CreateApiServerRequest{}
	return &this
}

// GetApiServerUrl returns the ApiServerUrl field value
func (o *CreateApiServerRequest) GetApiServerUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ApiServerUrl
}

// GetApiServerUrlOk returns a tuple with the ApiServerUrl field value
// and a boolean to check if the value has been set.
func (o *CreateApiServerRequest) GetApiServerUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApiServerUrl, true
}

// SetApiServerUrl sets field value
func (o *CreateApiServerRequest) SetApiServerUrl(v string) {
	o.ApiServerUrl = v
}

// GetDescription returns the Description field value
func (o *CreateApiServerRequest) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *CreateApiServerRequest) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *CreateApiServerRequest) SetDescription(v string) {
	o.Description = v
}

// GetOwnedBy returns the OwnedBy field value if set, zero value otherwise.
func (o *CreateApiServerRequest) GetOwnedBy() int64 {
	if o == nil || IsNil(o.OwnedBy) {
		var ret int64
		return ret
	}
	return *o.OwnedBy
}

// GetOwnedByOk returns a tuple with the OwnedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateApiServerRequest) GetOwnedByOk() (*int64, bool) {
	if o == nil || IsNil(o.OwnedBy) {
		return nil, false
	}
	return o.OwnedBy, true
}

// HasOwnedBy returns a boolean if a field has been set.
func (o *CreateApiServerRequest) HasOwnedBy() bool {
	if o != nil && !IsNil(o.OwnedBy) {
		return true
	}

	return false
}

// SetOwnedBy gets a reference to the given int64 and assigns it to the OwnedBy field.
func (o *CreateApiServerRequest) SetOwnedBy(v int64) {
	o.OwnedBy = &v
}

func (o CreateApiServerRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateApiServerRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["apiServerUrl"] = o.ApiServerUrl
	toSerialize["description"] = o.Description
	if !IsNil(o.OwnedBy) {
		toSerialize["ownedBy"] = o.OwnedBy
	}
	return toSerialize, nil
}

func (o *CreateApiServerRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"apiServerUrl",
		"description",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateApiServerRequest := _CreateApiServerRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateApiServerRequest)

	if err != nil {
		return err
	}

	*o = CreateApiServerRequest(varCreateApiServerRequest)

	return err
}

type NullableCreateApiServerRequest struct {
	value *CreateApiServerRequest
	isSet bool
}

func (v NullableCreateApiServerRequest) Get() *CreateApiServerRequest {
	return v.value
}

func (v *NullableCreateApiServerRequest) Set(val *CreateApiServerRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateApiServerRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateApiServerRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateApiServerRequest(val *CreateApiServerRequest) *NullableCreateApiServerRequest {
	return &NullableCreateApiServerRequest{value: val, isSet: true}
}

func (v NullableCreateApiServerRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateApiServerRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
